#### NumPy - Scientific Computing Package

#### Vectors
- ordered collection of numbers
- elements of a vector are of same type
- denoted by lowercase bold letters $\mathbf{x}$ or by placing a arrow on top $\vec{x}$
- *dimension* or *rank* refers to size of a vector (no of values in the vector)

$$\vec{x} = \begin{pmatrix} x_1 \\ x_2 \\ x_3 \\ x_4 \\ x_n \end{pmatrix}$$

- this vector $\vec{x}$ has a dimension of `n`


#### VECTOR CREATION

In [9]:
import numpy as np
import time

# allocates memory for vector and initialize with values
# input - dimension of the vector
a = np.zeros(4)
print(f'np.zeros(4): a = {a}, shape = {a.shape}, type = {a.dtype}')

b = np.zeros((4,4))
print(f'np.zeros(4,4): b = {b}, shape = {b.shape}, type = {b.dtype}')

c = np.random.random_sample(4)
print(f"np.random.random_sample(4): c = {c}, shape = {c.shape}, type = {c.dtype}")

# don't take dimension as input
d = np.arange(4.)
print(f'np.arange(4.): d = {d}, shape = {d.shape}, type = {d.dtype}')

np.zeros(4): a = [0. 0. 0. 0.], shape = (4,), type = float64
np.zeros(4,4): b = [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape = (4, 4), type = float64
np.random.random_sample(4): c = [0.85798898 0.63886846 0.12890689 0.4723475 ], shape = (4,), type = float64
np.arange(4.): d = [0. 1. 2. 3.], shape = (4,), type = float64


#### Operations on Vectors

In [13]:
e = np.array([1,2,3,4,5])

print(-e)
print(e ** 2)
print(np.sum(e))

f = -e
print(e + f)

[-1 -2 -3 -4 -5]
[ 1  4  9 16 25]
15
[0 0 0 0 0]


#### DOT PRODUCT
- multiplies values in two vectors element wise and sums all the products
- dot product require the dimension of vectors to be same

<img src="./res/dot_product.gif" width=500>

#### Comparing Execution Speed of doing dot product using loop & using numpy

In [14]:
np.random.seed(1)

# let's generate a huge data set
a = np.random.rand(1_00_00_000)
b = np.random.rand(1_00_00_000)

# let's calculate the time taken with loops
res = 0
start = time.time()

for i in range(a.shape[0]):
    res += a[i] * b[i]

end = time.time()
print(f'loop | result = {res}, time taken = {1000 * (end - start):.4f} ms')


# let's calculate the time taken with np.dot function
start = time.time()

res = np.dot(a, b)

end = time.time()
print(f'np.dot | result = {res}, time taken = {1000 * (end - start):.4f} ms')

loop | result = 2501072.5816813707, time taken = 3219.1055 ms
np.dot | result = 2501072.5816813167, time taken = 8.0655 ms


Based on the consumed time it's clear that, vectorization provides a large speed up in this example. <br/>
This is because NumPy makes better use of available data parallelism in the underlying hardware. GPU's and modern CPU's implement Single Instruction, Multiple Data (SIMD) pipelines allowing multiple operations to be issued in parallel. This is critical in Machine Learning where the data sets are often very large.

In [17]:
x = np.array([[1], [2], [3], [4]])   
print(x.shape)    # (4, 1) - means a 2D matrix, with only 1 column -> column vector
                  # has 4 rows and 1 column
                  # [ [1],
                  #   [2],
                  #   [3],
                  #   [4] ]
print(x[0].shape)

(4, 1)
(1,)


#### MATRIX CREATION

In [35]:
a = np.zeros((5, 3))  # matrix with 5 rows and 3 column
print(f'a = {a}, shape = {a.shape}')

b = np.zeros((1, 3))  # matrix with 1 rows and 3 column
print(f'\n\nb = {b}, shape = {b.shape}')

c = np.zeros((3, 1))  # matrix with 3 rows and 1 column
print(f'\n\nc = {c}, shape = {c.shape}')

d = np.zeros((1, 1))  # matrix with 1 rows and 1 column
print(f'\n\nd = {d}, shape = {d.shape}\n\n')


# arange - generates 1D array of numbers b/w 1 to 6
# 2  - specify we need a 2D matrix of column 2
# -1 - specify automatic row deterimination based on the no of values & column count
e = np.arange(6).reshape(-1, 2)
print(e, end="\n\n")

# in summary, (-1, 2) specify I need a matrix of two columns but automatically determine
# the no of rows based on the no of elements and column size

f = np.arange(6).reshape(2, -1)
print(f)

a = [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape = (5, 3)


b = [[0. 0. 0.]], shape = (1, 3)


c = [[0.]
 [0.]
 [0.]], shape = (3, 1)


d = [[0.]], shape = (1, 1)


[[0 1]
 [2 3]
 [4 5]]

[[0 1 2]
 [3 4 5]]


##### SLICING IN NUMPY

In [43]:
a = np.arange(20).reshape(-1, 10)
print(a, end="\n\n")

slice1 = a[0, 1:5]
print(slice1, end="\n\n")

slice2 = a[:, 1:5]
print(slice2, end="\n\n")

slice3 = a[1, :]
print(slice3, end="\n\n")

print(a[1,4], end="\n\n")

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]

[1 2 3 4]

[[ 1  2  3  4]
 [11 12 13 14]]

[10 11 12 13 14 15 16 17 18 19]

14

